FROM maven:3.9.6-eclipse-temurin-21 AS build

COPY src /app/src
COPY pom.xml /app

WORKDIR /app
RUN mvn clean install -DskipTests

FROM eclipse-temurin:21-jre

COPY --from=build /app/target/first_app-0.0.1-SNAPSHOT.jar /app.jar

WORKDIR /app
EXPOSE 2004

CMD ["java", "-jar", "/app.jar"]